'use client'

import { ArrowLeft, ChevronRight, Database, RefreshCw } from 'lucide-react'
import { useState } from 'react'
import { MetricCard, StatusBadge } from './shared'
import { statusLabels, statusMap, type SetView } from './types'
import { resultService, testSessionService, protocolService } from '@/lib/services'

export function SessionsFeature({ setView }: { setView: SetView }) {
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const sessionRecords = testSessionService.listSync()
  if (selectedId) return <SessionDetail sessionId={selectedId} onBack={() => setSelectedId(null)} />
  return <div className="content"><div className="page-actions"><div><div className="eyebrow">UNIFIED TEST SESSIONS</div><h2>测试会话</h2><p>来自客户端、设备、文件导入与 API 的统一数据记录</p></div><div className="action-group"><button className="secondary-button" onClick={() => setView('sources')}><Database size={16} />数据源</button><button className="primary-button" onClick={() => setView('testing')}>手动开始 <ChevronRight size={16} /></button></div></div><div className="metric-grid"><MetricCard label="本月会话" value="126" trend="+18.6% 较上月" icon={Database} /><MetricCard label="分析完成" value="118" trend="93.7% 已发布" icon={RefreshCw} /><MetricCard label="处理中" value="5" trend="平均 42 秒" icon={RefreshCw} /></div><section className="panel table-panel"><div className="panel-heading"><div><h3>最近会话</h3><span>统一状态模型 · LOCAL → RECEIVED → ANALYZED → PUBLISHED</span></div></div><div className="table-scroll"><table><thead><tr><th>会话</th><th>运动员</th><th>协议</th><th>来源</th><th>状态</th><th /></tr></thead><tbody>{sessionRecords.map(session => <tr key={session.id} className="clickable-row" onClick={() => setSelectedId(session.id)}><td><strong>#{session.id}</strong><span>{session.trialCount} trials · raw data</span></td><td>{session.athleteName}</td><td>{session.protocolName}</td><td><span className="test-pill">{session.source}</span></td><td><StatusBadge status={session.status === 'PUBLISHED' ? 'normal' : session.status.includes('FAILED') ? 'attention' : 'warning'} /></td><td><ChevronRight size={16} className="muted-icon" /></td></tr>)}</tbody></table></div></section></div>
}

function SessionDetail({ sessionId, onBack }: { sessionId: string; onBack: () => void }) {
  const session = testSessionService.getSync(sessionId)!
  const result = resultService.getSync(sessionId)
  return <div className="content"><button className="back-link" onClick={onBack}><ArrowLeft size={15} />返回测试会话</button><div className="page-actions"><div><div className="eyebrow">TEST SESSION DETAIL</div><h2>#{session.id}</h2><p>{session.athleteName} · {session.protocolName}</p></div><StatusBadge status={session.status === 'PUBLISHED' ? 'normal' : session.status.includes('FAILED') ? 'attention' : 'warning'} /></div><div className="session-detail-grid"><section className="panel session-info"><h3>会话信息</h3><dl><dt>数据源</dt><dd>{session.source}</dd><dt>设备</dt><dd>{session.device}</dd><dt>开始时间</dt><dd>{session.startedAt}</dd><dt>生命周期</dt><dd>{statusLabels[session.status]}</dd></dl></section><section className="panel result-preview-card"><span className="protocol-kicker">RESULT</span><div className="result-hero"><strong>{result?.primary.value ?? session.primaryResult}</strong><span>{result?.primary.unit ?? ''}<br />{result?.primary.label ?? '主结果'}</span></div>{result && <div className="result-metrics">{Object.entries(result.metrics).map(([key, value]) => <div key={key}><span>{key}</span><strong>{value}</strong></div>)}</div>}</section></div><section className="panel timeline-panel"><div className="panel-heading"><div><h3>处理历史</h3><span>原始数据 → 验证 → 分析 → 发布</span></div></div><div className="sync-rows">{['RECEIVED', 'VALIDATING', 'PROCESSING', session.status].map((status, index) => <div className="sync-row" key={`${status}-${index}`}><span className="sync-state received">✓</span><div><strong>{statusLabels[status as keyof typeof statusLabels]}</strong><span>{session.id} · {session.source}</span></div><em>{index === 3 ? '当前' : `${index + 1} 分钟前`}</em></div>)}</div></section></div>
}
